# Data and/or Sample access request

Access to **biobanked samples** and/or **individual-level data** of the **Flemish HBM studies** is granted on request and subject to approval.

---

## Who can request access?

Sample and/or Data access requests can be submitted by stakeholders for research projects in the public interest, in line with the objectives of the Flemish HBM studies.

---

## Data access procedure

### Step-by-step

1. Submits a **Sample and/or Data Access Request Form** 

  - Via [**Microsoft Forms**](https://forms.office.com/e/P6mNCN0MHS).
      - To preprare for a form submission, you may consult the corresponding word version [here][to be established].
  - Provide the required annexes via e-mail as instructed in the form. 
      - Selection of [**studies**](/downloads/10.5281_zenodo.18940001)
      - Selection of [**variables**](/downloads/10.5281_zenodo.20273218) 
      - Selection of [**samples**](https://doi.org/10.5281/zenodo.18939890)
      
      
2. The request is reviewed by the **Flemish Supervisory Board**
3. If approved, access is granted:
   - to the requested Flemish HBM biobanked samples
   - to the requested subset of Flemish HBM data (studies and variables),
   - **only after signature of the applicable agreements** 
     - Data Controller Agreement[LINK to be included]
     - Material Transfer Agreement[LINK to be included]
4. Approved samples are made available via the Biobank manager
5. Approved data extracts are made available via the Flemish HBM Data Platform manager (contact)
  



---



### Annex – Studies

Download the **Annex – Studies** file(s) [here](/downloads/10.5281_zenodo.18940001).

For each study you request:
- set **`request_stud_1isYes` = 1**

✅ All studies marked with `request_stud_1isYes = 1` are included in the request.

### Annex – Variables

Download the **Annex – Variables** file(s) [here](/downloads/10.5281_zenodo.20273218)

For each variable you request:
- set **`request_var_1isYes` = 1**

✅ All variables marked with `request_var_1isYes = 1` are included in the request.


### Annex – Samples
Download the **Annex – Samples** file(s) [here](https://doi.org/10.5281/zenodo.18939890).

For each sample type you request:

- set **`request_sample_1isYes` = 1**
- fill out: request_sample_volume - indicate the requested minimal volume per sample
- fill out: request_sample_n - indicate the number of requested samples
- fill out: request_sample_remarks - when applicable, provide remarks

✅ All studies marked with `request_sample_1isYes = 1` are included in the request.


## Questions?

For questions on access to data and/or samples from the Flemish HBM Studies, contact the Flemish HBM supervisory board: [TZC@provincieantwerpen.be](mailto:TZC@provincieantwerpen.be)

For assistance in submitting a request to obtain access to samples and/or data, contact: [flehs.datamanagement@vito.be](mailto:flehs.datamanagement@vito.be)






